language: php
php:
  - 5.6

before_script:
  - echo -e "Host 104.236.118.124\n\tStrictHostKeyChecking no" >> ~/.ssh/config

before_install:
  - openssl aes-256-cbc -K $encrypted_4dc565c56c51_key -iv $encrypted_4dc565c56c51_iv -in .travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d  

matrix:
  allow_failures:
    - php: 5.6

after_success:
  - bash .travis/deploy.sh
