language: php

before_install:
- openssl aes-256-cbc -K $encrypted_4dc565c56c51_key -iv $encrypted_4dc565c56c51_iv
  -in travis_rsa.enc -out travis_rsa -d
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    all_branches: true